# Generated by Django 5.2 on 2026-06-22 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Scheme name (e.g. CBSE Default)', max_length=50)),
                ('min_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(help_text='Grade label (A1, A2, B1…)', max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='Optional GPA point', max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grading_schemes',
                'ordering': ['-min_percent'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('guardian_name', models.CharField(max_length=120)),
                ('guardian_contact', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('unit_test', 'Unit Test'), ('mid_term', 'Mid Term'), ('final', 'Final'), ('practical', 'Practical')], max_length=20)),
                ('term', models.CharField(blank=True, max_length=20, null=True)),
                ('weightage', models.DecimalField(blank=True, decimal_places=2, help_text='Percent this exam contributes to the overall grade', max_digits=5, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('published', 'Published')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='app1.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='app1.class')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='student.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_subjects', to='app1.subject')),
            ],
            options={
                'db_table': 'exam_subjects',
                'unique_together': {('exam', 'class_id', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnalysisSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank_in_section', models.IntegerField(blank=True, null=True)),
                ('subject_breakdown', models.JSONField(default=dict, help_text='Per-subject scores at this point')),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_analysis_snapshots', to='app1.academicyear')),
                ('exam', models.ForeignKey(blank=True, help_text='Snapshot point (after which exam)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='student.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshots', to='student.student')),
            ],
            options={
                'db_table': 'student_analysis_snapshots',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPerformanceNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('strength', 'Strength'), ('concern', 'Concern'), ('observation', 'Observation'), ('improvement', 'Improvement')], max_length=15)),
                ('note_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, help_text='Optional link to an exam', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_notes', to='student.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_notes', to='student.student')),
                ('subject', models.ForeignKey(blank=True, help_text='Subject-specific note (null = general note)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_performance_notes', to='app1.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_performance_notes_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_performance_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSuccessNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('behavioral', 'Behavioral'), ('attendance', 'Attendance'), ('parental', 'Parental'), ('intervention', 'Intervention')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('at_risk', 'At Risk')], default='info', max_length=10)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('note_text', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_notes', to='student.student')),
                ('success_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='success_notes_authored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_success_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Score (null if absent)', max_digits=6, null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade, computed from grading_schemes', max_length=5, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('entry_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published')], default='draft', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin who later overrode (audited)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks_updated', to=settings.AUTH_USER_MODEL)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.examsubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='student.student')),
            ],
            options={
                'db_table': 'exam_marks',
                'unique_together': {('exam_subject', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='student.student')),
            ],
            options={
                'db_table': 'student_attendance',
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('promoted', 'Promoted'), ('repeated', 'Repeated'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='active', max_length=15)),
                ('enrolled_on', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='app1.academicyear')),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='app1.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='app1.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'db_table': 'student_enrollments',
                'ordering': ['-academic_year__start_date'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
